version: 0.2
phases:
  pre_build:
    commands:
      - cd react-demo
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-path: no
  base-directory: build
